// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// The user side (loader). It loads the eBPF program into the kernel
// (the verifier checks it), attaches it to the execve tracepoint, then
// reads events off the ring buffer and prints them.

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <bpf/libbpf.h>
#include "hello.skel.h"   /* generated by `bpftool gen skeleton` */
#include "hello.h"

static volatile bool exiting = false;

static void sig_handler(int sig)
{
	exiting = true;
}

/* Called once per event delivered through the ring buffer. */
static int handle_event(void *ctx, void *data, size_t data_sz)
{
	const struct event *e = data;

	printf("%-8d %-8d %-16s %s\n", e->pid, e->ppid, e->comm, e->filename);
	return 0;
}

int main(int argc, char **argv)
{
	struct ring_buffer *rb = NULL;
	struct hello_bpf *skel;
	int err;

	/* Quiet libbpf's info logs. Comment this out if you want to debug. */
	libbpf_set_print(NULL);

	signal(SIGINT, sig_handler);
	signal(SIGTERM, sig_handler);

	/* 1. Open + load the eBPF object into the kernel (verifier runs here). */
	skel = hello_bpf__open_and_load();
	if (!skel) {
		fprintf(stderr, "Failed to open/load BPF skeleton (need root?)\n");
		return 1;
	}

	/* 2. Attach to the execve tracepoint. */
	err = hello_bpf__attach(skel);
	if (err) {
		fprintf(stderr, "Failed to attach BPF program: %d\n", err);
		goto cleanup;
	}

	/* 3. Set up the user-side ring buffer reader. */
	rb = ring_buffer__new(bpf_map__fd(skel->maps.rb), handle_event, NULL, NULL);
	if (!rb) {
		err = -1;
		fprintf(stderr, "Failed to create ring buffer\n");
		goto cleanup;
	}

	printf("%-8s %-8s %-16s %s\n", "PID", "PPID", "COMM", "FILENAME");
	printf("Tracing execve()... open another terminal and run something. Ctrl-C to stop.\n");

	/* 4. Poll for events until interrupted. */
	while (!exiting) {
		err = ring_buffer__poll(rb, 100 /* ms timeout */);
		if (err == -EINTR) {
			err = 0;
			break;
		}
		if (err < 0) {
			fprintf(stderr, "Error polling ring buffer: %d\n", err);
			break;
		}
	}

cleanup:
	ring_buffer__free(rb);
	hello_bpf__destroy(skel);
	return err < 0 ? -err : 0;
}
